# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd8cea0850036d604ad251532f695e3282b3d66e50d7bcef0b359fdd6bc4739b77177364e199edf8b42753ae6845f88d0ce3ea9a8e30a508ec9aa336c6e9a520

test:
  secret_key_base: f7cdfd8747a20d9da7d2018b9b94dc7150e6763c50d239fdaba0a2b4963f194c379786cadca3ca7ee6b0b14162064bd1d02e32a5ef3acd423b97c0cac43a096c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
